### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by pythonmobile** [bdarnell/tornado-production-skeleton#2]
Any chance we can get an updated deployment doc for 2021 / version 6+? (especially with nginx + multiple processes http_server.bind()+IOLoop.current.start()). Thanks.

**Comment by bdarnell** [comment]
I don't intend to make any updates to this repo; it makes more sense to open an issue in tornadoweb/tornado for updated deployment docs. We have [some docs on nginx](https://www.tornadoweb.org/en/stable/guide/running.html) there. I don't know if there's anything out of date there; it's been a long time since I've personally worked with nginx (or been responsible for any HTTP load balancer). This is probably more of an area for community contributions than something I'd produce. 

I also want to [deprecate multi-process mode](https://www.tornadoweb.org/en/stable/guide/running.html) so that won't feature in any updated docs.
